### ISSUE TITLE
Support IngressClass changes in IngressController  v1.0.0 (post 1.22 upgrades)

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/aergia-controller#8]
It looks like https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.0.0 doesn't play nicely with Aergia after the k8s 1.22 upgrades in PR #7 

https://kubernetes.github.io/ingress-nginx/#what-is-an-ingressclass-and-why-is-it-important-for-users-of-ingress-nginx-controller-now

I've pinned it to the last 0.x release for now, but we'll need to add support in to this.  It may just be a test anomoly.

**Comment by tobybellwood** [comment]
Error message when loading ingress under 4.0.1
```
W0831 00:49:33.918625 8 controller.go:1007] Service "example-nginx/example-nginx-svc" does not have any active Endpoint.
I0831 00:49:33.942946 8 main.go:101] "successfully validated configuration, accepting" ingress="example-ingress/example-nginx"
I0831 00:49:33.945102 8 store.go:361] "Ignoring ingress because of error while validating ingress class" ingress="example-nginx/example-ingress" error="ingress does not contain a valid IngressClass"```

**Comment by tobybellwood** [comment]
I'm currently working around it in testing with the following config in ingress-nginx-values.yaml
```
controller:
  watchIngressWithoutClass: true
  ingressClassResource:
    default: true
```

**Comment by shreddedbacon** [comment]
Pretty sure this is no longer required
